use std::fs;

use phpantom_lsp::Backend;
use tower_lsp::LanguageServer;
use tower_lsp::lsp_types::*;

/// A trimmed-down `.castor.stub.php`: braced namespace blocks holding
/// the helpers the task files call. Hidden *and* gitignored.
const CASTOR_STUB: &str = r#"<?php

// This file has been generated by castor. Do not edit it manually.

namespace Castor {
    function run(string $command): void {}
    function io(): void {}
}
"#;

/// A task file inside the hidden `.castor/` directory.
const DOCKER_TASKS: &str = r#"<?php

namespace docker;

function up(): void {}
"#;

/// The root `castor.php`, calling into both of the above.
const CASTOR_TASKS: &str = r#"<?php

use function Castor\io;
use function Castor\run;
use function docker\up;

function build(): void
{
    io();
    run('make build');
    up();
}
"#;

/// Build a Castor-shaped workspace whose `[indexing] include` is set to
/// `include`.
async fn castor_workspace(include: &[&str]) -> (Backend, tempfile::TempDir) {
    let dir = tempfile::tempdir().expect("failed to create temp dir");
    let root = dir.path();

    // `ignore` only honours `.gitignore` inside a git repository, so the
    // gitignored half of the fixture needs a repo to be realistic.
    fs::create_dir_all(root.join(".git")).unwrap();
    fs::write(root.join(".gitignore"), "/.castor.stub.php\n").unwrap();
    fs::write(root.join(".castor.stub.php"), CASTOR_STUB).unwrap();
    fs::create_dir_all(root.join(".castor")).unwrap();
    fs::write(root.join(".castor/docker.php"), DOCKER_TASKS).unwrap();
    fs::write(root.join("castor.php"), CASTOR_TASKS).unwrap();

    let entries: Vec<String> = include
        .iter()
        .map(|entry| format!("{entry:?}"))
        .collect::<Vec<_>>();
    fs::write(
        root.join(".phpantom.toml"),
        format!("[indexing]\ninclude = [{}]\n", entries.join(", ")),
    )
    .unwrap();

    let backend = Backend::new_test_with_workspace(root.to_path_buf(), Vec::new());
    backend.initialized(InitializedParams {}).await;

    let uri = Url::from_file_path(root.join("castor.php")).unwrap();
    backend
        .did_open(DidOpenTextDocumentParams {
            text_document: TextDocumentItem {
                uri,
                language_id: "php".into(),
                version: 1,
                text: CASTOR_TASKS.into(),
            },
        })
        .await;

    (backend, dir)
}

fn tasks_uri(dir: &tempfile::TempDir) -> Url {
    Url::from_file_path(dir.path().join("castor.php")).unwrap()
}

async fn goto(backend: &Backend, uri: &Url, line: u32, character: u32) -> Option<Location> {
    let response = backend
        .goto_definition(GotoDefinitionParams {
            text_document_position_params: TextDocumentPositionParams {
                text_document: TextDocumentIdentifier { uri: uri.clone() },
                position: Position { line, character },
            },
            work_done_progress_params: WorkDoneProgressParams::default(),
            partial_result_params: PartialResultParams::default(),
        })
        .await
        .unwrap();

    match response {
        Some(GotoDefinitionResponse::Scalar(location)) => Some(location),
        Some(GotoDefinitionResponse::Array(mut locations)) => {
            (!locations.is_empty()).then(|| locations.remove(0))
        }
        _ => None,
    }
}

/// Without the option nothing changes: both hidden paths stay invisible.
/// This is the bug report, and it pins the default behaviour so the
/// option cannot silently become unconditional.
#[tokio::test]
async fn without_include_hidden_paths_stay_unindexed() {
    let (backend, dir) = castor_workspace(&[]).await;
    let uri = tasks_uri(&dir);

    assert!(
        goto(&backend, &uri, 9, 5).await.is_none(),
        "`run` is only declared in the gitignored stub"
    );
    assert!(
        goto(&backend, &uri, 10, 5).await.is_none(),
        "`up` is only declared in the hidden directory"
    );

    let mut diags = Vec::new();
    backend.collect_unknown_function_diagnostics(uri.as_str(), CASTOR_TASKS, &mut diags);
    assert_eq!(
        diags.len(),
        3,
        "io/run/up should all be unknown, got: {diags:?}"
    );
}

#[tokio::test]
async fn include_resolves_function_from_gitignored_stub() {
    let (backend, dir) = castor_workspace(&[".castor", ".castor.stub.php"]).await;
    let uri = tasks_uri(&dir);

    let location = goto(&backend, &uri, 9, 5)
        .await
        .expect("`run` should resolve to the included stub");
    assert_eq!(
        location.uri,
        Url::from_file_path(dir.path().join(".castor.stub.php")).unwrap()
    );
    assert_eq!(location.range.start.line, 5, "Castor\\run is on line 5");
}

#[tokio::test]
async fn include_resolves_function_from_hidden_directory() {
    let (backend, dir) = castor_workspace(&[".castor", ".castor.stub.php"]).await;
    let uri = tasks_uri(&dir);

    let location = goto(&backend, &uri, 10, 5)
        .await
        .expect("`up` should resolve inside the included hidden directory");
    assert_eq!(
        location.uri,
        Url::from_file_path(dir.path().join(".castor/docker.php")).unwrap()
    );
}

#[tokio::test]
async fn include_clears_unknown_function_diagnostics() {
    let (backend, dir) = castor_workspace(&[".castor", ".castor.stub.php"]).await;
    let uri = tasks_uri(&dir);

    let mut diags = Vec::new();
    backend.collect_unknown_function_diagnostics(uri.as_str(), CASTOR_TASKS, &mut diags);
    assert!(
        diags.is_empty(),
        "included declarations must clear the unknown-function diagnostics, got: {diags:?}"
    );
}

#[tokio::test]
async fn include_feeds_hover() {
    let (backend, dir) = castor_workspace(&[".castor", ".castor.stub.php"]).await;
    let uri = tasks_uri(&dir);

    // `io();` on line 8.
    let hover = backend
        .hover(HoverParams {
            text_document_position_params: TextDocumentPositionParams {
                text_document: TextDocumentIdentifier { uri },
                position: Position {
                    line: 8,
                    character: 5,
                },
            },
            work_done_progress_params: WorkDoneProgressParams::default(),
        })
        .await
        .unwrap()
        .expect("hover should resolve a function from the included stub");

    let text = match hover.contents {
        HoverContents::Markup(markup) => markup.value,
        other => panic!("expected markup hover, got: {other:?}"),
    };
    assert!(
        text.contains("function io()"),
        "hover should show the stub signature, got: {text}"
    );
}

/// A missing entry must not break indexing of the entries beside it.
#[tokio::test]
async fn include_tolerates_missing_entries() {
    let (backend, dir) = castor_workspace(&["does/not/exist", ".castor.stub.php"]).await;
    let uri = tasks_uri(&dir);

    assert!(
        goto(&backend, &uri, 9, 5).await.is_some(),
        "the stub should still be indexed alongside a stale entry"
    );
}
